// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cybernetlab/swimming-search/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Booking is an autogenerated mock type for the Booking type
type Booking struct {
	mock.Mock
}

// GetCentres provides a mock function with given fields: ctx
func (_m *Booking) GetCentres(ctx context.Context) ([]domain.Centre, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCentres")
	}

	var r0 []domain.Centre
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Centre, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Centre); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Centre)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartSearchCourses provides a mock function with given fields: ctx, search, out
func (_m *Booking) StartSearchCourses(ctx context.Context, search domain.Search, out chan<- domain.Course) {
	_m.Called(ctx, search, out)
}

// NewBooking creates a new instance of Booking. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBooking(t interface {
	mock.TestingT
	Cleanup(func())
}) *Booking {
	mock := &Booking{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
