// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	bot "github.com/cybernetlab/swimming-search/internal/controller/bot"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/cybernetlab/swimming-search/internal/usecase"
)

// CommandHandler is an autogenerated mock type for the CommandHandler type
type CommandHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *CommandHandler) Execute(_a0 *usecase.UseCase, _a1 *bot.Command) {
	_m.Called(_a0, _a1)
}

// NewCommandHandler creates a new instance of CommandHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandHandler {
	mock := &CommandHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
