// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/cybernetlab/swimming-search/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// DeleteSearch provides a mock function with given fields: ctx, search
func (_m *Store) DeleteSearch(ctx context.Context, search domain.Search) error {
	ret := _m.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSearch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Search) error); ok {
		r0 = rf(ctx, search)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: ctx, name
func (_m *Store) DeleteUser(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCentres provides a mock function with given fields: ctx
func (_m *Store) GetCentres(ctx context.Context) ([]domain.Centre, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCentres")
	}

	var r0 []domain.Centre
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Centre, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Centre); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Centre)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSearch provides a mock function with given fields: ctx, userName
func (_m *Store) GetSearch(ctx context.Context, userName string) (domain.Search, domain.NodeID, error) {
	ret := _m.Called(ctx, userName)

	if len(ret) == 0 {
		panic("no return value specified for GetSearch")
	}

	var r0 domain.Search
	var r1 domain.NodeID
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Search, domain.NodeID, error)); ok {
		return rf(ctx, userName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Search); ok {
		r0 = rf(ctx, userName)
	} else {
		r0 = ret.Get(0).(domain.Search)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) domain.NodeID); ok {
		r1 = rf(ctx, userName)
	} else {
		r1 = ret.Get(1).(domain.NodeID)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, userName)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetSearches provides a mock function with given fields: ctx, nodeID
func (_m *Store) GetSearches(ctx context.Context, nodeID domain.NodeID) ([]domain.Search, error) {
	ret := _m.Called(ctx, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for GetSearches")
	}

	var r0 []domain.Search
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.NodeID) ([]domain.Search, error)); ok {
		return rf(ctx, nodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.NodeID) []domain.Search); ok {
		r0 = rf(ctx, nodeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Search)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.NodeID) error); ok {
		r1 = rf(ctx, nodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, name
func (_m *Store) GetUser(ctx context.Context, name string) (domain.User, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx
func (_m *Store) GetUsers(ctx context.Context) ([]domain.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutCentres provides a mock function with given fields: ctx, centres
func (_m *Store) PutCentres(ctx context.Context, centres []domain.Centre) error {
	ret := _m.Called(ctx, centres)

	if len(ret) == 0 {
		panic("no return value specified for PutCentres")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Centre) error); ok {
		r0 = rf(ctx, centres)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutSearch provides a mock function with given fields: ctx, search
func (_m *Store) PutSearch(ctx context.Context, search domain.Search) error {
	ret := _m.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for PutSearch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Search) error); ok {
		r0 = rf(ctx, search)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutUser provides a mock function with given fields: ctx, user
func (_m *Store) PutUser(ctx context.Context, user domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for PutUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
